<?php
// This file is automatically generated by setup.php.
// Do not modify manually!!

$g_schoolname = 'Eastern Visayas State University - ORMOC City Campus';
$g_schoolname_short = 'EVSU-OCC';
$g_schooladdress = 'Ormoc City';
$g_dbhostname = 'localhost';
$g_dbname = 'evsudb';
$g_dbusername = 'root';
//$g_dbpassword = 'c2VjcmV0';
$g_dbpassword = '';
?>
