<?php
// This php script is to create conf.php
// Run this script from command line as following to configure your SSU Accounting System.
//   # php -f setup.php

$stdin = fopen('php://stdin','r');

function get_data( $description, $default_val )
{
	global $stdin;
	echo "Enter $description [$default_val] :";
	$input = trim( fgets($stdin) );
	if( $input!='' ) return $input;
	return $default_val;
}

echo "Configuring SSU Accounting System\n";
echo "Answer following question.\n";

$schoolname = get_data( "school name", "Samar State University" );
$schoolname_short = get_data( "short name for school", "SSU" );
$schooladdress = get_data( "address of the school", "Catbalogan, Samar" );
$hostname = get_data( "hostname of database", "localhost" );
$dbname = get_data( "name of database", "" );
$username = get_data( "username of database", "" );
$password = get_data( "password of database", "" );

$fp = fopen( "conf.php", "w" );
if( ! $fp )  die( "error creating file" );
fputs( $fp, "<?php\n" );
fputs( $fp, "// This file is automatically generated by setup.php.\n" );
fputs( $fp, "// Do not modify manually!!\n\n" );
fputs( $fp, "\$g_schoolname = '$schoolname';\n" );
fputs( $fp, "\$g_schoolname_short = '$schoolname_short';\n" );
fputs( $fp, "\$g_schooladdress = '$schooladdress';\n" );
fputs( $fp, "\$g_dbhostname = '$hostname';\n" );
fputs( $fp, "\$g_dbname = '$dbname';\n" );
fputs( $fp, "\$g_dbusername = '$username';\n" );
fputs( $fp, "\$g_dbpassword = '" . base64_encode($password) . "';\n" );
fputs( $fp, "?>\n" );
fclose($fp);

echo "Successfully configured!";
?>
